'use client';
import {useState} from 'react';
import type {Job} from '../assessment/model';
import {stats,risk,formatRange} from './logic';
import {routeTitle} from '../assessment/presentation';
import s from './profile.module.css';
export default function AiOptions({shortlist,links,onOpen,onExplore}:{shortlist:Job[];links:Map<string,Job[]>;onOpen:(j:Job,start?:string)=>void;onExplore:()=>void}){
 const [chosen,setChosen]=useState<string[]|null>(null);const selected=(chosen??shortlist.slice(0,3).map(j=>j.id)).filter(id=>shortlist.some(j=>j.id===id));
 return <section className={s.panel}><header className={s.intro}><span>AI & YOUR OPTIONS</span><h1>Look at the work.<br/><em>Ask what could change.</em></h1><p>Compare your saved options, then explore the tasks behind the scores.</p></header>
 <div className={s.aiLegend}><div><span>01</span><h2>Exposure</h2><p>How much of the work AI may be able to learn.</p></div><div><span>02</span><h2>Substitution</h2><p>Whether AI could replace the work.</p></div><div><span>03</span><h2>AI risk</h2><p>The two combined. An estimate, not a job-loss probability.</p></div></div>
 {!shortlist.length?<div className={s.next}><div><h2>Choose something to investigate.</h2><p>Add careers or training routes to your shortlist to compare them here.</p></div><button onClick={onExplore}>Explore options →</button></div>:<><div className={s.sectionHead}><h2>Compare up to three</h2><span>{selected.length}/3 selected</span></div><div className={s.chips}>{shortlist.map(j=><button aria-pressed={selected.includes(j.id)} disabled={selected.length>=3&&!selected.includes(j.id)} key={j.id} onClick={()=>setChosen(selected.includes(j.id)?selected.filter(id=>id!==j.id):[...selected,j.id])}>{selected.includes(j.id)?'✓ ':''}{routeTitle(j.label,j.path)}</button>)}</div><div className={s.comparison}>{shortlist.filter(j=>selected.includes(j.id)).map(j=>{const r=stats(j,links).risk;return <article key={j.id}><small>{j.path==='jobs'?'Career':j.path==='degrees'?'Degree':'Apprenticeship'}</small><h2>{routeTitle(j.label,j.path)}</h2>{j.path==='jobs'?<div className={s.aiBars}>{[['Exposure',j.exposure],['Substitution',j.substitution],['AI risk',risk(j)]].map(([label,value])=><div key={String(label)}><span>{String(label)}</span><strong>{value==null?'Not available':`${Math.round(Number(value))}/100`}</strong><meter min="0" max="100" value={Number(value) || 0} aria-label={`${label}: ${value==null?'not available':Math.round(Number(value))}`} data-unknown={value==null}/></div>)}</div>:<div className={s.routeRisk}><small>AI risk across linked careers</small><strong>{formatRange(r)}</strong><p>{r.min===null?'Scores not available':`${r.total-r.missing} of ${r.total} linked careers have scores`}</p></div>}<button onClick={()=>onOpen(j,'AI & tasks')}>{j.path==='jobs'?'Explore the tasks':'Explore linked careers'} ↗</button></article>;})}</div><p className={s.note}>These estimates describe occupations, not you. Missing data stays unknown. Training routes can lead to careers with different risks.</p></>}
 <section className={s.block}><h2>Questions worth asking</h2><div className={s.questionCards}><div><span>THE TASKS</span><h3>What could AI help with?</h3><p>Look for tasks that may change, and tasks that still need people.</p></div><div><span>THE WORKPLACE</span><h3>What happens in practice?</h3><p>Ask someone doing the work how their tools and responsibilities are changing.</p></div><div><span>YOUR PLAN</span><h3>What could you try next?</h3><p>A conversation, a course visit, or a small practical activity.</p></div></div></section>
 <details className={s.note}><summary>How to read the scores</summary><p>AI risk is the geometric mean of exposure and substitution. Career exposure and substitution use the current percentile scales. Task learnability scores use a different scale. The underlying tasks describe US occupations, with UK pay and opening figures elsewhere in Pathfinder. These are estimates, not predictions or entry advice.</p></details>
 </section>;
}
