'use client';
import type { Job, InterestData, Profile } from '../assessment/model';
import { defaults, sectorLabel } from './exploration';
import type { Exploration } from './exploration';
import s from './explore.module.css';
export default function ExploreControls({value,onChange,units,path,data,profile,complete}:{value:Exploration;onChange:(v:Exploration)=>void;units:Job[];path:string;data:InterestData;profile:Profile;complete:boolean}){
 const update=(patch:Partial<Exploration>)=>onChange({...value,...patch});
 const sectors=[...new Set(units.filter(j=>j.path===path).flatMap(j=>j.sectors))].sort((a,b)=>sectorLabel(a,units).localeCompare(sectorLabel(b,units)));
 const chosen=data.areas.filter(a=>profile.specificInterests[a.id]==='pursue');
 const adjusted=value.pay+value.ai+value.openings>0;
 return <details className={s.panel}><summary>Shape your exploration <span>{adjusted?'Your balance':value.sector||value.area||value.match||value.conflicts?'Filtered':'Profile-led'} · Filters & priorities</span></summary><div className={s.body}><div className={s.filters}><label>{path==='jobs'?'Career group':path==='degrees'?'Subject area':'Sector'}<select value={value.sector} onChange={e=>update({sector:e.target.value})}><option value="">All areas</option>{sectors.map(k=><option key={k} value={k}>{sectorLabel(k,units)}</option>)}</select></label><label>Your chosen interests<select value={value.area} onChange={e=>update({area:e.target.value})} disabled={!chosen.length}><option value="">All interests</option>{chosen.map(a=><option key={a.id} value={a.id}>{a.label}</option>)}</select></label><label>Interest match<select value={value.match} onChange={e=>update({match:Number(e.target.value)})} disabled={!complete}><option value={0}>Any match</option><option value={70}>70+ /100</option><option value={80}>80+ /100</option><option value={90}>90+ /100</option></select></label><label className={s.check}><input type="checkbox" checked={value.conflicts} disabled={!complete} onChange={e=>update({conflicts:e.target.checked})}/>Hide known conflicts with my must-haves / must-avoids</label></div><div className={s.balance}><h3>What matters most?</h3><p>Turn up a priority to bring those options forward.</p>{([['fit','Your profile'],['pay','Higher pay'],['ai','Lower AI impact'],['openings','More openings']] as const).map(([key,label])=><label className={s.slider} key={key}><span>{label}<output>{value[key]===0?'Off':`${value[key]}/5`}</output></span><input aria-label={`${label} priority`} type="range" min="0" max="5" value={value[key]} disabled={key==='fit'&&!complete} onChange={e=>update({[key]:Number(e.target.value)})}/></label>)}<label>AI measure<select value={value.metric} onChange={e=>update({metric:e.target.value})}><option value="risk">Combined AI risk</option><option value="exposure">AI exposure</option></select></label></div><footer><button onClick={()=>onChange({...defaults})}>Reset exploration ↺</button><details><summary>How this works</summary><p>Filters narrow the list. Priorities change its order; your interest-match score stays the same. Pay and openings use UK career-group comparisons. Training routes use averages across linked careers, so check the range on each card. Missing figures earn no points for that priority. A chosen-interest filter includes careers with an area score of at least 50/100, or routes linked to one. No known conflict does not guarantee a fit. AI exposure and risk are estimates, not job-loss probabilities.</p></details></footer></div></details>;
}
