'use client';
import {useState} from 'react';
import {DIMENSIONS,interests} from '../assessment/model';
import type {InterestData,Profile} from '../assessment/model';
import {CONFIDENCE,PREFERENCES,PREFERENCE_LABELS,SKILLS} from './journey';
import type {Journey} from './journey';
import s from './profile.module.css';
export default function ProfilePanel({profile,journey,data,onEdit,onExplore}:{profile:Profile;journey:Journey;data:InterestData;onEdit:(section:string)=>void;onExplore:()=>void}){
 const [tab,setTab]=useState('Overview');const values=interests(profile.answers),answered=profile.answers.every(n=>n>0);
 const priorities=data.areas.filter(a=>(journey.points[a.id]??0)>0).sort((a,b)=>journey.points[b.id]-journey.points[a.id]);
 const top=values.map((value,i)=>({value,label:DIMENSIONS[i]})).sort((a,b)=>b.value-a.value).slice(0,2);
 return <section className={s.panel}><header className={s.intro}><span>YOUR PROFILE</span><h1>Start with<br/><em>yourself.</em></h1><p>What you enjoy. What matters. What you could build on.</p></header><nav className={s.tabs} aria-label="Profile sections">{['Overview','Interests','Confidence','Working life'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='Overview'?<><div className={s.overview}><button onClick={()=>setTab('Interests')}><small>WHAT YOU ENJOY</small><h2>{answered?(Math.max(...values)-Math.min(...values)<6?'A broad mix of interests':top.map(t=>t.label).join(' & ')):'Still to explore'}</h2><span>Your interests ↗</span></button><button onClick={()=>setTab('Working life')}><small>WHAT MATTERS</small><h2>{PREFERENCES.filter(p=>journey.preferences[p.id]===1).slice(0,2).map(p=>p.label).join(' · ')||'Room to explore'}</h2><span>Your working life ↗</span></button><button onClick={()=>setTab('Confidence')}><small>WHAT YOU COULD BUILD ON</small><h2>{SKILLS.filter(k=>(journey.confidence[k.id]??0)>=4).slice(0,2).map(k=>k.label).join(' & ')||'Skills to try and practise'}</h2><span>Your confidence ↗</span></button></div><section className={s.block}><h2>Your priorities</h2><div className={s.priorities}>{priorities.map(a=><div key={a.id}><strong>{a.label}</strong><span>{journey.points[a.id]}<small>/10 points</small></span><meter min="0" max="10" value={journey.points[a.id]} aria-label={a.label}/></div>)}</div>{!priorities.length&&<p>No priorities chosen yet.</p>}</section><div className={s.next}><div><small>NEXT: EXPLORE</small><h2>Turn curiosity into questions.</h2><p>Save a few options, then look at how AI could change the work.</p></div><button onClick={onExplore}>Explore options →</button></div></>:
 tab==='Interests'?<section className={s.block}><div className={s.sectionHead}><h2>What you enjoy</h2><button onClick={()=>onEdit('activities')}>Review answers ↗</button></div><div className={s.bars}>{DIMENSIONS.map((label,i)=><div key={label}><span>{label}</span><meter min="0" max="100" value={answered?(values[i]-10)/40*100:0} aria-label={label}/><small>{answered?`${Math.round((values[i]-10)/40*100)}/100`:'Not answered'}</small></div>)}</div><p className={s.note}>Your answers describe interests, not ability.</p><div className={s.sectionHead}><h2>Your chosen interests</h2><button onClick={()=>onEdit('interests')}>Review choices ↗</button></div><div className={s.chips}>{priorities.map(a=><span key={a.id}>{a.label} · {journey.points[a.id]}/10</span>)}</div></section>:
 tab==='Confidence'?<section className={s.block}><div className={s.sectionHead}><h2>Skills you can develop</h2><button onClick={()=>onEdit('skills')}>Review answers ↗</button></div><div className={s.confidence}>{SKILLS.map(k=><div key={k.id}><strong>{k.label}</strong><p>{k.scenario}</p><div className={s.dots} aria-label={`${journey.confidence[k.id]??0} of 5 confidence`}>{[1,2,3,4,5].map(n=><i key={n} data-filled={(journey.confidence[k.id]??0)>=n}/>)}</div><span>{journey.confidence[k.id]===undefined?'Not answered':journey.confidence[k.id]===0?'Not tried yet':CONFIDENCE[journey.confidence[k.id]-1]}</span></div>)}</div><p className={s.note}>Stated confidence, not a skills test. These answers do not rule careers in or out.</p></section>:
 <section className={s.block}><div className={s.sectionHead}><h2>What matters to you</h2><button onClick={()=>onEdit('preferences')}>Review answers ↗</button></div><div className={s.preferenceRows}>{PREFERENCES.map(p=><div key={p.id}><strong>{p.label}</strong><span data-essential={journey.preferences[p.id]===1||journey.preferences[p.id]===5}>{PREFERENCE_LABELS[(journey.preferences[p.id]??0)-1]??'Not answered'}</span></div>)}</div></section>}
 </section>;
}
