'use client';
/* eslint-disable @next/next/no-img-element */
import type { Dispatch, SetStateAction, RefObject } from 'react';
import type { InterestData, Profile } from '../assessment/model';
import { STAGES } from '../assessment/model';
import { CONFIDENCE, PREFERENCE_LABELS, PREFERENCES, SKILLS, stages, allocationValid } from './journey';
import type { Journey } from './journey';
import s from './pathfinder.module.css';

export const INTRO = {
 activities:{text:'Find work you might enjoy.',art:'making',label:'What you enjoy'},
 interests:{text:'Choose what interests you most.',art:'ideas',label:'Your interests'},
 skills:{text:'See what you can build on.',art:'science',label:'Your confidence'},
 preferences:{text:'Find work that suits your life.',art:'people',label:'Your working life'},
 education:{text:'Help us suggest your next steps.',art:'making',label:'Your next steps'},
};
export function Introduction({name,onContinue}:{name:keyof typeof INTRO;onContinue:()=>void}){const intro=INTRO[name];return <div className={s.sectionIntro} key={name}><div><span className={s.eyebrow}>{intro.label}</span><h1 tabIndex={-1}>{intro.text}</h1><button className={s.primary} onClick={onContinue} autoFocus>Continue <span aria-hidden="true">↗</span></button></div><img src={`/pathfinder-art/${intro.art}.png`} width="512" height="512" alt=""/></div>;}
export default function QuizSections({step,data,profile,setProfile,journey,setJourney,go,answer,finish,canFinish,fieldsDone,setFieldsDone,heading}:{step:number;data:InterestData;profile:Profile;setProfile:Dispatch<SetStateAction<Profile>>;journey:Journey;setJourney:Dispatch<SetStateAction<Journey>>;go:(n:number)=>void;answer:()=>void;finish:()=>void;canFinish:boolean;fieldsDone:boolean;setFieldsDone:(v:boolean)=>void;heading:RefObject<HTMLHeadingElement|null>}){
 const st=stages(data.areas.length);
 const nav=(next:boolean=true)=><div className={s.questionNav}><button className={s.textButton} onClick={()=>go(step-1)}>← Back</button><button className={s.textButton} disabled={!next} onClick={()=>go(step+1)}>Next →</button></div>;
 if(step<st.allocation){const area=data.areas[step-61],chosen=profile.specificInterests[area.id];return <div className={s.interestQuestion}><span className={s.eyebrow}>Would you like to explore this?</span><h1 ref={heading} tabIndex={-1}>{area.label}</h1><p>{area.description}</p><div className={s.binaryChoices}>{[['avoid','×','Not for me'],['pursue','✓','Yes, explore']].map(([value,glyph,label])=><button key={value} aria-pressed={chosen===value} className={chosen===value?s.selected:''} onClick={()=>{setProfile(p=>({...p,specificInterests:{...p.specificInterests,[area.id]:value as 'pursue'|'avoid'}}));setJourney(j=>{const points={...j.points};if(value==='avoid')delete points[area.id];return {...j,points};});setFieldsDone(false);answer();go(step+1);}}><span aria-hidden="true">{glyph}</span>{label}</button>)}</div><div className={s.questionNav}><button className={s.textButton} onClick={()=>go(step-1)}>← Back</button><span>{step-60} / {data.areas.length}</span><button className={s.textButton} disabled={!chosen||chosen==='neutral'} onClick={()=>go(step+1)}>Next →</button></div></div>;}
 if(step===st.allocation){const selected=data.areas.filter(a=>profile.specificInterests[a.id]==='pursue'),total=selected.reduce((n,a)=>n+(journey.points[a.id]??0),0),reviewed=data.areas.every(a=>['pursue','avoid'].includes(profile.specificInterests[a.id]));return <div className={s.allocation}><span className={s.eyebrow}>Your priorities</span><h1 ref={heading} tabIndex={-1}>{selected.length?'What draws you most?':'Nothing caught your eye?'}</h1><p>{selected.length?'Share 10 points across your choices. Give more to what matters most.':'You can revisit the areas or continue with your activity answers.'}</p>{selected.length>0&&<><div className={s.pointWallet} aria-live="polite"><strong>{10-total}</strong><span>points left</span><div aria-hidden="true">{Array.from({length:10},(_,i)=><i key={i} className={i<total?s.usedPoint:''}/>)}</div></div><div className={s.pointRows}>{selected.map(a=><div className={s.pointRow} key={a.id}><span>{a.label}</span><div><button aria-label={`Remove point from ${a.label}`} disabled={!journey.points[a.id]} onClick={()=>{setFieldsDone(false);setJourney(j=>({...j,points:{...j.points,[a.id]:(j.points[a.id]??0)-1}}));}}>−</button><output aria-label={`${a.label} points`}>{journey.points[a.id]??0}</output><button aria-label={`Add point to ${a.label}`} disabled={total===10} onClick={()=>{setFieldsDone(false);setJourney(j=>({...j,points:{...j.points,[a.id]:(j.points[a.id]??0)+1}}));answer();}}>+</button></div></div>)}</div>{selected.length===1&&total===0&&<button className={s.secondary} onClick={()=>{setJourney(j=>({...j,points:{[selected[0].id]:10}}));answer();}}>Give this choice all 10 points</button>}</>}{!reviewed&&<p className={s.questionHint}>Finish the tick/cross choices first.</p>}<div className={s.questionNav}><button className={s.textButton} onClick={()=>go(61)}>← Review areas</button><button className={s.primary} disabled={!reviewed||!allocationValid(journey,profile,data.areas)} onClick={()=>{setFieldsDone(true);if(!fieldsDone)answer();go(step+1);}}>Continue ↗</button></div></div>;}
 if(step<st.preferences){const skill=SKILLS[step-st.skills];return <div className={s.questionPage}><span className={s.eyebrow}>{skill.label} · How confident would you feel?</span><h1 ref={heading} tabIndex={-1}>{skill.scenario}</h1><div className={s.answerScale}>{CONFIDENCE.map((label,i)=><button key={label} className={journey.confidence[skill.id]===i+1?s.selected:''} aria-pressed={journey.confidence[skill.id]===i+1} onClick={()=>{setJourney(j=>({...j,confidence:{...j.confidence,[skill.id]:i+1}}));answer();go(step+1);}}><span className={s.answerGlyph} aria-hidden="true">{['·','○','◔','◕','●'][i]}</span>{label}</button>)}</div><button className={`${s.textButton} ${s.notTried}`} aria-pressed={journey.confidence[skill.id]===0} onClick={()=>{setJourney(j=>({...j,confidence:{...j.confidence,[skill.id]:0}}));answer();go(step+1);}}>Not tried this</button><p className={s.questionHint}>Confidence can grow. This isn’t a test of ability.</p>{nav(journey.confidence[skill.id]!==undefined)}</div>;}
 if(step<st.education){const pref=PREFERENCES[step-st.preferences];return <div className={s.questionPage}><span className={s.eyebrow}>In your working life</span><h1 ref={heading} tabIndex={-1}>{pref.label}</h1><div className={s.answerScale}>{PREFERENCE_LABELS.map((label,i)=><button key={label} className={journey.preferences[pref.id]===i+1?s.selected:''} aria-pressed={journey.preferences[pref.id]===i+1} onClick={()=>{setJourney(j=>({...j,preferences:{...j.preferences,[pref.id]:i+1}}));answer();go(step+1);}}><span className={s.answerGlyph} aria-hidden="true">{['✳','+','~','−','×'][i]}</span>{label}</button>)}</div><p className={s.questionHint}>We’ll show where a career may conflict with your priorities.</p>{nav(journey.preferences[pref.id]!==undefined)}</div>;}
 return <div className={s.aboutPage}><span className={s.eyebrow}>Where you are now</span><h1 ref={heading} tabIndex={-1}>What comes next?</h1><label>What are you doing now?<select value={profile.stage} onChange={e=>setProfile(p=>({...p,stage:e.target.value}))}><option value="">Choose…</option>{STAGES.map(stage=><option key={stage}>{stage}</option>)}</select></label><label>How much study are you open to?<select value={profile.educationPlan} onChange={e=>setProfile(p=>({...p,educationPlan:e.target.value as Profile['educationPlan']}))}><option value="">Choose…</option><option value="gcse">Finish GCSEs, then work or train</option><option value="level3">A levels, college, or an apprenticeship</option><option value="university">A degree</option><option value="postgraduate">A degree and further study</option><option value="unsure">I’m open to ideas</option></select></label><div className={s.questionNav}><button className={s.textButton} onClick={()=>go(step-1)}>← Back</button><button className={s.primary} disabled={!profile.stage||!profile.educationPlan||!canFinish} onClick={finish}>Find my paths ↗</button></div>{!canFinish&&<p className={s.questionHint}>Finish each section to see your suggestions. Your answers are kept when you go back.</p>}</div>;
}
